language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/IRLSizeExample.xcworkspace
  - IOS_SDK=iphonesimulator9.2
  - EXAMPLE_SCHEME="IRLSizeExample"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"      POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus" POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPad 2"         POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPad Pro"       POD_LINT="YES"
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcrun simctl list

  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
